apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair-postgres-old
  labels:
    quay-component: clair-postgres-old
  annotations:
    quay-component: clair-postgres-old
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      quay-component: clair-postgres-old
  template:
    metadata:
      labels:
        quay-component: clair-postgres-old
    spec:
      terminationGraceperiodSeconds: 600
      serviceAccountName: clair-postgres
      volumes:
        - name: clair-postgres-conf-sample
          configMap:
            name: clair-postgres-conf-sample
        - name: postgres-data
          persistentVolumeClaim:
            claimName: clair-postgres-13
      initContainers:
      - name: init-postgres-config
        image: quay.io/sclorg/postgresql-13-c9s:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            # Wait for PostgreSQL to be ready
            until pg_isready; do
              echo "Waiting for PostgreSQL to be ready..."
              sleep 2
            done
            
            # Modify configuration files
            echo "password_encryption = 'scram-sha-256'" >> $PGDATA/postgresql.conf
            echo "host    all    all    0.0.0.0/0    scram-sha-256" >> $PGDATA/pg_hba.conf
            
            # Reload configuration
            pg_ctl reload
            
            # Set password for postgres user
            psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
        env:
          - name: PGDATA
            value: /var/lib/pgsql/data
          - name: PGHOST
            value: localhost
          - name: PGUSER
            value: postgres
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/pgsql/data
      containers:
        - name: postgres
          image: quay.io/sclorg/postgresql-13-c9s:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: clair-postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
